version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Official actions have moving tags like v1
      # that are used, so they don't need updates here
      - dependency-name: "actions/*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for pip dependencies
    open-pull-requests-limit: 0
