# Required
version: 2

# Image to use
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
